Repository traPtitech/traPortfolio-UI, pull requests merged in 2024-10, with the labels that each got.

#226 update some dependencies
  package-lock.json
Labels: Review effort [1-5]: 2

#227 replace: our University name
  index.html
  src/components/Layout/PageFooter.vue
  src/pages/IndexPage.vue
Labels: Review effort [1-5]: 2

#228 delete: prism
  package-lock.json
  package.json
Labels: Review effort [1-5]: 1

#230 main ブランチへの名称変更に対応
  .github/workflows/main.yml
  .github/workflows/staging.yml
Labels: Review effort [1-5]: 1

#197 router-linkのto属性でオブジェクトを使用するように
  src/components/Contest/ContestTeamListItem.vue
  src/components/ContestTeam/MemberListItem.vue
  src/components/Contests/ContestListItem.vue
  src/components/Event/HostnameListItem.vue
  src/components/Events/EventListItem.vue
  src/components/Group/AdminListItem.vue
  src/components/Group/MemberListItem.vue
  src/components/Groups/GroupListItem.vue
  src/components/Index/GroupList.vue
  src/components/Layout/BreadCrumbTrail.vue
  src/components/Layout/PageHeader.vue
  src/components/Project/MemberListItem.vue
  src/components/Projects/ProjectListItem.vue
  src/components/Search/UserListItem.vue
  src/components/User/ContestsContainer.vue
  src/lib/param.ts
  src/pages/ContestPage.vue
  src/pages/ContestTeamPage.vue
  src/pages/ContestsPage.vue
  src/pages/GroupPage.vue
  src/pages/GroupsPage.vue
  src/pages/ProjectPage.vue
  src/pages/ProjectsPage.vue
  src/pages/UserPage.vue
Labels: Review effort [1-5]: 3

#232 ESLint v9 に対応
  .eslintrc.cjs
  eslint.config.js
  package-lock.json
  package.json
  src/components/ContestTeam/MemberListItem.vue
  src/components/Event/HostnameListItem.vue
  src/components/Group/MemberListItem.vue
  src/components/Index/TopSection.vue
  src/components/Search/UserListItem.vue
  src/components/User/EventsContainer.vue
  src/components/User/UserDetailContainer.vue
  src/lib/apis/index.ts
  src/pages/ContestPage.vue
  src/pages/EventPage.vue
  src/pages/EventsPage.vue
  src/pages/SearchPage.vue
Labels: Review effort [1-5]: 3

#231 Dev/buildImagePerPR
  .github/workflows/preview-comment.yaml
  .github/workflows/preview.yaml
Labels: Review effort [1-5]: 3

#235 fix: added genApi step before build image
  .github/workflows/preview.yaml
Labels: Review effort [1-5]: 2

#234 fix: ESLint と Prettier の競合を解消した (Prettier に寄せた)
  .prettierrc
  eslint.config.js
  src/App.vue
  src/components/Contest/ContestTeamListItem.vue
  src/components/ContestTeam/MemberListItem.vue
  src/components/Event/HostnameListItem.vue
  src/components/Events/EventList.vue
  src/components/Group/AdminList.vue
  src/components/Group/AdminListItem.vue
  src/components/Group/MemberListItem.vue
  src/components/Groups/GroupList.vue
  src/components/Index/TopSection.vue
  src/components/Layout/BreadCrumbTrail.vue
  src/components/Layout/PageContainer.vue
  src/components/Layout/PageFooter.vue
  src/components/Project/MemberListItem.vue
  src/components/Search/UserListItem.vue
  src/components/UI/AIcon.vue
  src/components/UI/ExternalLink.vue
  src/components/UI/SearchInput.vue
  src/components/User/AccountList.vue
  src/components/User/AccountListItem.vue
  src/components/User/ContestsContainer.vue
  src/components/User/EventsContainer.vue
  src/components/User/ProjectsContainer.vue
  src/components/User/UserDetailContainer.vue
  src/pages/GroupPage.vue
  src/pages/IndexPage.vue
  src/pages/ProjectPage.vue
Labels: Review effort [1-5]: 3

#216 rimrafのpackageを消した
  package-lock.json
  package.json
Labels: Review effort [1-5]: 2
